### ISSUE TITLE
Why designator descriptions as lists of lists?

### ISSUE THREAD

**Issue by airballking** [cram-code/cram_core#29]
Our designator descriptions are lists of lists. Conceptually, however, we always refer to them as lists of key-value pairs. 

For a list of key-value pairs, Common LISP has standard representations (alist, plist, or hash-table). Would it make sense to switch our internal representations of designator descriptions to for instance alists? It could mean less custom code, and more standard Common LISP code.

@moesenle @gaya- @fairlight1337 @gheorghelisca @yazdani @bbrieber @mpomarlan

**Comment by fairlight1337** [comment]
Nice idea. Besides the fact that it requires major refactoring of *lots* of code (that uses designator descriptions), its probably smart to do that.

From a logging perspective, no problems should arise. There is one serializer- and one deserializer-function that could easily be adapted. For the rest, though, we would need to touch a lot of stuff.

**Comment by gaya-** [comment]
I would propose to keep the internal representation as is and write a getter function that would convert the internal list of lists into a list of alists and give it back. As designator descriptions are read-only anyway and writing ```'((key1 value1) (key2 value2))``` is prettier than ```'((key1 . value1) (key2 . value2))``` having a ```(description-alist my-designator)``` return a converted list of alists should be enough.

**Comment by fairlight1337** [comment]
True. Accessing the designator's description should happen through a function call, such as `(description ...)` anyway and not through slot access :).

I like @gaya-'s proposition.

**Comment by airballking** [comment]
My original intention was to improve our implementation of designators by internally using standard data-structures. I think we should not maintain code to access/manipulate collections of key-value pairs when there is such code available in Common LISP or Alexandria.

That being said, I think having  designator descriptions (through setter and and getter functions) appear like such a datastructure to users would already be an improvement.

As for conveniently creating designators in code, I personally would prefer such an interface (omitting the type for clarity):
```lisp
(with-designators ((desig (:key1 value1 :key2 value2 :key3 value3))))
```

**Comment by moesenle** [comment]
Hi Georg,

in Common Lisp, an alist is essentially just a list whose elements are
again cons cells. The CAR of these cons cells are interpreted a key while
the CDR is the corresponding value. That's exactly what designator
descriptions are in the end, so we already use alists there. It just needs
to be noted that the value in the current solution is always a list, most
often with just one element.

I designed it that way deliberately since it is based on standard Common
Lisp's alists and I explicitly wanted to support values which are longer
than one element. To avoid special handling for one element values vs.
multiple element values I decided to use lists everywhere. In the current
implementation, you can, if you want, already write explicit alist-syntax
with the dot. For instance `(foo bar)` would become `(foo . (bar))`.

To summerize, the current implementation already uses alists.

I see a problem with plists though. They are just flat lists. I always
found it quite hard to work with them and supporting multiple values for a
key is not as easy. In addition, I don't like to write (to pick location
foo) instead of ((to pick) (location foo)).

Regarding hash tables, I think they are a bit of overkill. The underlying
data structure of a hash table is an array where the index is computed by
hashing the key. This implies that that array is quite big to not require
reallocations too often. Just creating a hash table for every designator
description feels like wasting a lot of memory. A second problem would be
that creating hash-tables is much more inconvenient than creating
lists/alists.

Lorenz

**Comment by gaya-** [comment]
Sorry, wanted to cancel my comment and instead closed the issue :)

I think I like the representation ```(:to pick :location foo)```. It can get confusing when the value is a keyword too though: ```(:to :pick :location ,loc)``` vs ```((:to :pick) (:location ,loc))```

**Comment by fairlight1337** [comment]
So, given Lorenz' comments, and the fact that there is wanting for an alternative signature for `with-designators`, would it make sense to just introduce a new signature in that macro? It should be pretty straight forward to detect whether the property list for a newly generated designator is similar to either `((key1 value1) (key2 value2) ...)` or `(:key1 value1 :key2 value2)`. This way, we wouldn't need to change too much, but get the new functionality for the sake of clarity.

What do you think?

**Comment by airballking** [comment]
Hi Lorenz,

thanks for the long comment! I take away that we are currently already using a standard Common LISP data-structure. Namely, a special type of alist, that is, one that always has lists as values. As a result, we automatically support multiple values for the same key. Thanks for pointing this out!

I also just verified that the ```alexandria``` methods for converting alists also work on designator descriptions. I stand corrected! :)

Finally, liking/disliking plists is a question of personal taste, and the memory overhead of hash-tables is obvious.

For me, my original question has been sufficiently answered. Hence, I close the issue.
