### ISSUE TITLE
Who can explain this particalur behavior of ```with-task-suspended```?

### ISSUE THREAD

**Issue by airballking** [cram-code/cram_core#34]
I'm playing around with task suspension, and encountered some behavior which I cannot explain to myself. I destillled the problem to the following toy example:

``` lisp
(top-level
  (cpl-impl:with-tags
    (cpl-impl:par
      (:tag suspending-task
        (cpl:sleep 0.5)
        (cpl-impl:with-task-suspended (suspended-task)
          (format t "successfully suspended task~%")))
      (:tag suspended-task
        (format t "starting task~%")
        (cpl:sleep 1)
        (format t "in the middle of task~%")
        (cpl:sleep 1)
        (format t "finishing task~%")))))
```

Which prints:

```
starting task
successfully suspended task
in the middle of task
finishing task
```

This is what I expected. If I replace `cpl::sleep` with the regular `sleep` function in the suspended task, the suspension mechanism seems to break:

``` lisp
(top-level
  (cpl-impl:with-tags
    (cpl-impl:par
      (:tag suspending-task
        (cpl:sleep 0.5)
        (cpl-impl:with-task-suspended (suspended-task)
          (format t "successfully suspended task~%")))
      (:tag suspended-task
        (format t "starting task~%")
        (sleep 1)
        (format t "in the middle of task~%")
        (sleep 1)
        (format t "finishing task~%")))))
```

Which prints:

```
starting task
in the middle of task
finishing task
successfully suspended task
```

Apparently, the suspending task is waiting for the suspend task to completely finish. In other words, the suspended task ignores the request for suspension. I tried to find any suspension-specific code `cpl:sleep` but came up empty.

To be clear, I would have hoped for this:

```
starting task
in the middle of task
successfully suspended task
finishing task
```

Meaning, as soon as the first `sleep` is through, suspension should be possible.

Who can explain this behavior? @moesenle @gaya- @fairlight1337 @yazdani @gheorghelisca

**Comment by moesenle** [comment]
Hi Georg,

right. That's what I would expect :) If you want to sleep, you must use the
CPL version of `sleep`. And here comes the explanation:

In cram, suspension, evaporation, etc. works through a simple messaging
mechanism. Basically, every cram thread periodically checks its mailbox and
if suspension is requested waits until it is woken up before continuing
with normal program execution. This periodic checking is done via deadlines
on IO operations. When the deadline is reached, a signal is raised, the
mailbox is handled and the deadline is deferred to enter the deadline
handler again later. Unfortunately, this relies on IO functions to respect
deadlines, i.e. signal the deadline signal when the deadline is reached.
Even more unfortunately, SBCL's sleep function does not respect these
deadlines so we had to implement our own deadline function.

Lorenz

**Comment by airballking** [comment]
Hi Lorenz,

thanks for your insightful and fast answer! Good to hear that this is indeed a feature and not a bug. :)

In my example ```sleep``` is a stand-in for any action called through ```send-goal-and-wait``` which takes time. ```send-goal-and-wait``` internally uses some sort of sleep mechanism to wait for the right message from the server. Should sneaking ```cpl::sleep``` into that spot make ```send-goal-and-wait``` support suspending?

**Comment by moesenle** [comment]
Hi,

that's just a problem with the implementation of `send-goal-and-wait` that
was introduced in the new implementation of actionlib-lisp. The new
implementation polls for 'is-done' periodically, i.e. it sleeps. That's
just not how it should be done. The correct solution there would be to use
a condition variable in combination with a mutex to notify the waiting
thread that data has been received. You can steal the corresponding code
from my old action client implementation if you want.

Btw. I think actions should also be cancelled when a calling task is
suspended or evaporated. My old actionlib implementation handled that by
calling cancel inside an unwind-protect in send-goal-and-wait. I always
found that really convenient because that way, actions were always
cancelled when I stopped plan execution by pressing C-c C-c. You might want
to consider re-adding this feature.

Lorenz

**Comment by airballking** [comment]
Hi Lorenz,

implementing ```send-goal-and-wait``` using a condition variable together with a mutex instead of polling sounds interesting. I will study your old implementation to figure out what you have been doing there!

How does this relate to the original question of "cram task rely on periodic checking done via deadlines on IO operations"? I do not see the connection. Could you please point me to specific pieces of code?

Cheers,
Georg.

P.S.: We already followed your suggested of wrapping ```send-goal-and-wait``` in an unwind-protect with ```cancel-goal```, when you made it the first time. ;) It is a good idea!

**Comment by moesenle** [comment]
Hey Georg,

How does this relate to the original question of "cram task rely on
> periodic checking done via deadlines on IO operations"? I do not see the
> connection. Could you please point me to specific pieces of code?
>
>
the original question was about sleep and task suspension, right? You
pointed out that the sleep in your example stands for `send-goal-and-wait`
which internally uses sleep. That made me wonder because in my experience,
sleeps are only very rarely required and are normally a clear code smell
that things can be improved. I believe "sneaking cpl::sleep into that spot
in send-goal-and-wait" is not the best solution so I pointed out how
`send-goal-and-wait` can be improved to support suspending. Sorry if I
didn't make that clear.

Lorenz
